local diagnostic_goto = function(next, severity)
    local go = next and vim.diagnostic.goto_next or vim.diagnostic.goto_prev
    severity = severity and vim.diagnostic.severity[severity] or nil
    return function()
        go({ severity = severity })
    end
end
vim.keymap.set("n", "]d", diagnostic_goto(true), { desc = "Next Diagnostic" })
vim.keymap.set("n", "[d", diagnostic_goto(false), { desc = "Prev Diagnostic" })
vim.keymap.set("n", "]e", diagnostic_goto(true, "ERROR"), { desc = "Next Diagnostic ERROR" })
vim.keymap.set("n", "[e", diagnostic_goto(false, "ERROR"), { desc = "Prev Diagnostic Error" })
vim.keymap.set("n", "]w", diagnostic_goto(true, "WARN"), { desc = "Next Diagnostic Warning" })
vim.keymap.set("n", "[w", diagnostic_goto(false, "WARN"), { desc = "Prev Diagnostic Warning" })
vim.keymap.set("n", "<leader>lw", vim.diagnostic.open_float, { desc = "Float Window View Diagnostic" })
vim.keymap.set("n", "<leader>lq", vim.diagnostic.setloclist, { desc = "QuickFix Window View Diagnostic" })

vim.keymap.set("n", "gD", vim.lsp.buf.declaration, { desc = "Goto Declaration" })
vim.keymap.set("n", "gd", vim.lsp.buf.definition, { desc = "Goto Definition" })
vim.keymap.set("n", "gy", vim.lsp.buf.type_definition, { desc = "Goto Type Definition" })
vim.keymap.set("n", "gI", vim.lsp.buf.implementation, { desc = "Goto Implementation" })
vim.keymap.set({ "n", "v" }, "<leader>lc", vim.lsp.buf.code_action, { desc = "Code Action" })
vim.keymap.set("n", "<leader>lC", GionVim.lsp.action.source, { desc = "Source Action" })
vim.keymap.set({ "n", "v" }, "<leader>le", vim.lsp.codelens.run, { desc = "Run Codelens" })
vim.keymap.set("n", "<leader>lE", vim.lsp.codelens.refresh, { desc = "Refresh & Display Codelens" })
vim.keymap.set("n", "<leader>lh", vim.lsp.buf.hover, { desc = "Hover" })
vim.keymap.set("n", "<leader>ls", vim.lsp.buf.signature_help, { desc = "Signature Help" })
vim.keymap.set("n", "<leader>lr", vim.lsp.buf.rename, { desc = "Rename Word" })
vim.keymap.set("n", "<leader>lR", function()
    Snacks.rename.rename_file()
end, { desc = "Rename File" })
vim.keymap.set("n", "<leader>ln", vim.lsp.buf.references, { desc = "References" })
vim.keymap.set("n", "<leader>li", vim.lsp.buf.incoming_calls, { desc = "Incoming" })
vim.keymap.set("n", "<leader>lo", vim.lsp.buf.outgoing_calls, { desc = "Outgoing" })
vim.keymap.set("n", "<leader>la", vim.lsp.buf.add_workspace_folder, { desc = "Add Workspace Folder" })
vim.keymap.set("n", "<leader>lm", vim.lsp.buf.remove_workspace_folder, { desc = "Remove Workspace Folder" })
vim.keymap.set("n", "<leader>lf", function()
    vim.lsp.buf.format({ async = true })
end, { desc = "LSP Async Format" })
